In [1]:
import numpy as np

In [2]:
input_str = "hheieotrk"
letters = [l for l in input_str]

In [ ]:
# Ceasar Square Decryption

matrix = np.array(letters).reshape(3, 3)
matrix = matrix.transpose()
print(matrix)

[['h' 'i' 't']
 ['h' 'e' 'r']
 ['e' 'o' 'k']]


In [ ]:
# ASCII Value Conversion

input_str = "83 104 97 114 112 101 110 32 121 111 117 114 32 109 105 110 100 46"
values = input_str.split()

for i in values:
  print(chr(int(i)), end = "")

Sharpen your mind.

In [ ]:
# Convert to laundry

input_str = "Sharpen your mind."

for i in input_str:
  print(ord(i), end = " ")

83 104 97 114 112 101 110 32 121 111 117 114 32 109 105 110 100 46 

In [15]:
A = np.array([2, 3, 4, 1]).reshape(2, 2)
B = np.array([104, 101, 121, 97, 108, 108]).reshape(2, 3)

C = np.dot(A, B)

print(C)

A_inv = np.linalg.inv(A)

# Recover B from C by multiplying with A_inv
B_again = A_inv.dot(C)

# Round to nearest integer and convert to int to match original B
B_again = np.rint(B_again).astype(int)

print(B_again)

[[499 526 566]
 [513 512 592]]
[[104 101 121]
 [ 97 108 108]]
